# yaml-language-server: $schema=https://www.schemastore.org/language-configuration.json

comments:
  lineComment: "'"

brackets:
  - [(, )]

autoClosingPairs:
  - [(, )]
  - ['"', '"']

surroundingPairs:
  - [(, )]
  - ['"', '"']
