name: Convert grammars to JSON for linguist

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'syntaxes/*.yml'

jobs:
  gen-json-grammars:
    if: github.repository == 'serkonda7/vscode-vba'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      -  uses: bait-lang/setup-bait@main
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run grammar converter and push changes
        run: bait run scripts/gen_json_grammar.bt
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
