# This github action checks if the grammar(s) in this repo will compile with the latest version of linguist.

name: Linguist Compilation Check
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout linguist
        uses: actions/checkout@v6
        with:
          repository: github-linguist/linguist

      - name: Checkout PR as submodule
        uses: actions/checkout@v6
        with:
          path: vendor/grammars/vscode-vba
          clean: false

      - name: Compile linguist grammar
        run: script/grammar-compiler add vendor/grammars/vscode-vba
