# This github action checks if the grammar(s) in this repo will compile with the latest version of linguist.

name: Linguist Compilation Check
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile-check:
    uses: serkonda7/linguist-compilation-action/.github/workflows/linguist.yml@vca99f3cf288972062696dc2f3dbe71ed885c8647
    with:
      repo: ${{ github.repository }}
